resources:
  containers:
  - container: pg11
    image: postgres:11
    environment:
        POSTGRES_PASSWORD: Password12!
        POSTGRES_USER: postgres

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - checkout: none

  - script: |
       docker run -d --name postgres10 -e POSTGRES_PASSWORD=Password12! -p 127.0.0.1:5432:5432 -v /var/run/postgresql:/var/run/postgresql postgres:11

  - script: |
       docker exec postgres10 psql -h 0.0.0.0 -U postgres -c "create database my_database"