resources:
  containers:
  - container: pg11
    image: postgres:11
    environment:
        POSTGRES_PASSWORD: Password12!
        POSTGRES_USER: postgres

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - checkout: none

  - script: |
      docker run -d --name postgres10 -e POSTGRES_PASSWORD=Password12! -p 54320:5432 postgres:10
      docker exec postgres10 psql -U postgres -c "create database testdatabase"