resources:
  containers:
  - container: my_container
    image: ubuntu:16.04
  - container: pg10
    image: postgres:10
 
pool:
  vmImage: 'ubuntu-16.04'

services:
  postgres: pg10
 
steps:

- checkout: none

- script: |
    sudo apt-get install -y postgresql-client
    sudo psql --host=postgres --username=postgres --command="SELECT 1;"
