resources:
  containers:
  - container: pg11
    image: postgres:11
    environment:
        POSTGRES_PASSWORD: Password12!
        POSTGRES_USER: postgres

pool:
  vmImage: 'ubuntu-16.04'
  #vmImage: 'windows-2019'

#container: mcr.microsoft.com/windows/servercore:1803

steps:
  - checkout: none
#-e MYSQL_PASSWORD=Password12! -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=testdata -e MYSQL_USER=test
  - script: |
       docker run -d --name mysql57 -e MYSQL_ROOT_PASSWORD=Password12! -e MYSQL_ROOT_HOST=% mysql:5.7
       until docker exec mysql57 mysql -e 'SELECT 1'; do
          >&2 echo "MySql is unavailable - sleeping"
          sleep 5
       done
       #docker exec mysql57 mysql -e 'CREATE DATABASE IF NOT EXISTS testdata DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'
       #docker exec mysql57 mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('Password12!');
       #                              GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';
       #                              FLUSH PRIVILEGES;"
       #docker exec mysql57 mysql -uroot -pPassword12! -e 'SELECT host,user FROM mysql.user;'
       #docker exec mysql57 mysql -e 'SELECT host,user FROM mysql.user;'
       docker exec mysql57 mysql -e 'SHOW DATABASES;'
       docker port mysql57
       docker ps

    displayName: Run MySQL container

  - script: |
      mysql h0.0.0.0 -P33060 -utest -pPassword12! -e 'SELECT * FROM mysql.user;'