
jobs:
- job: RunInContainer
  pool:
    vmImage: 'vs2017-win2016'

  steps:
    - checkout: none

    - powershell: |
            $sqlInstance = "(local)\SQL2014"
            # create databases
            $dbName = "TestDatanet45"
            Invoke-Sqlcmd -S "$sqlInstance" -Q "Use [master]; CREATE DATABASE [$dbName]"
      displayName: Install postgresql


    - script: printenv
