resources:
  containers:
  - container: pg11
    image: postgres:11
    environment:
        POSTGRES_PASSWORD: Password12!
        POSTGRES_USER: postgres

pool:
  vmImage: 'ubuntu-16.04'
  #vmImage: 'windows-2019'

#container: mcr.microsoft.com/windows/servercore:1803

steps:
  - checkout: none

  - script: |
       docker run --name mysql57 -e MYSQL_ROOT_PASSWORD=Passworn12! -d mysql:5.7

  - script: |
       while ! mysqladmin -h localhost ping --silent; do
          >&2 echo "MySql is unavailable - sleeping"
          sleep 1
       done
       docker exec mysql57 mysql -e 'CREATE DATABASE TestDatacore2 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci'