resources:
  containers:
  - container: pg11
    image: postgres:11
    environment:
        POSTGRES_PASSWORD: Password12!
        POSTGRES_USER: postgres

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - checkout: none

  - script: |
       docker run -d --name postgres10 -e POSTGRES_PASSWORD=Password12! -p 5432:5432 -v /var/run/postgresql:/var/run/postgresql postgres:9.6
  - script: |
       apt-get update && apt-get install -y postgresql-client
       psql -h localhost -p 5432 -U postgres -c "\du"