
jobs:
- job: RunInContainer
  pool:
    vmImage: 'vs2017-win2016'

  steps:
    - checkout: none
    - powershell: |
        $dbName = "TestDatanet45"
        $cmd = 'mysql -e "create database $dbName;" --user=root --password=Password12!'
        iex "& $cmd"
