
jobs:
- job: RunInContainer
  pool:
    vmImage: 'vs2017-win2016'

    services:
        postgres:
        image: postgres:9.4.5
        environment:
            - POSTGRES_USER=myapp

  steps:
    - checkout: none
    
    - powershell: |
        choco install postgresql10 --force --params '/Password:password'
        set PATH=%PATH%;"C:\Program Files\PostgreSQL\10\bin;C:\Program Files\PostgreSQL\10\lib"
        C:\Program Files\PostgreSQL\10\bin\createdb TestDatanet45
      displayName: Install postgresql

    - script: printenv
