resources:
  containers:
  - container: pg11
    image: postgres:11
    environment:
        POSTGRES_PASSWORD: Password12!
        POSTGRES_USER: postgres

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - checkout: none

  - script: |
      docker run --link postgres:postgres postgres:9.6 sh -c "exec psql -h \$POSTGRES_PORT_5432_TCP_ADDR -p \$POSTGRES_PORT_5432_TCP_PORT -U postgres"