resources:
  containers:
  - container: pg11
    image: postgres:11
    environment:
        POSTGRES_PASSWORD: Password12!
        POSTGRES_USER: postgres

pool:
  vmImage: 'win1803'

steps:
  - checkout: none

  - script: |
      docker run --name some-postgres -e POSTGRES_PASSWORD=Password12! -d postgres