resources:
  containers:
  - container: pg10
    image: postgres:10
    environment:
        POSTGRES_PASSWORD: Password12!
        POSTGRES_USER: postgres

pool:
  vmImage: 'ubuntu-16.04'

services:

  pg10: pg10

steps:
  - script: |
      sudo apt-get install -y postgresql-client
      sudo psql -c 'create database testdata;' -U postgres;