resources:
  containers:
  - container: my_container
    image: ubuntu:16.04
  - container: pg10
    image: postgres:10
    environment:
        POSTGRES_PASSWORD: Password12!
        POSTGRES_USER: postgres

pool:
  vmImage: 'ubuntu-16.04'

container: my_container

services:
  postgres: pg10

  steps:
  - script: |
      apt-get install -y postgresql-client
      psql --host=postgres --username=postgres --command="SELECT 1;"