
jobs:
- job: RunInContainer
  pool:
    vmImage: 'vs2017-win2016'

    services:
        postgres:
        image: postgres:9.4.5
        environment:
            - POSTGRES_USER=myapp

  steps:
    - checkout: none
    
    - script: |
        choco install postgresql10 --force --params '/Password:password'
        set PATH=%PATH%;C:\Program Files\PostgreSQL\10\bin;C:\Program Files\PostgreSQL\10\lib"
        echo "##vso[task.setvariable variable=PATH;]%PATH%;C:\Program Files\PostgreSQL\10\bin;C:\Program Files\PostgreSQL\10\lib"
        displayName: Install postgresql

    - script: printenv
