resources:
  containers:
  - container: my_container
    image: ubuntu:16.04
  - container: pg10
    image: postgres:10
 
pool:
  vmImage: 'ubuntu-16.04'
 

 
container: my_container
 
services:
  postgres: pg10
 
steps:

- checkout: none

- script: |
    apt install -y postgresql-client
    psql --host=postgres --username=postgres --command="SELECT 1;"
