
jobs:
- job: RunInContainer
  pool:
    vmImage: 'vs2017-win2016'

  steps:
    - checkout: none

    - powershell: |
        $env:PGUSER="postgres"
        $env:PGPASSWORD="Password12!"
        $dbName = "TestDatanet45"

        choco install postgresql9 --force --params '/Password:Password12!'
        set PATH=%PATH%;"C:\Program Files\PostgreSQL\9.6\bin;C:\Program Files\PostgreSQL\9.6\lib"
        $cmd = '"C:\Program Files\PostgreSQL\9.6\bin\createdb" $dbName'
        iex "& $cmd"
      displayName: Install postgresql


    - script: printenv
