resources:
  containers:
  - container: pg10
    image: postgres:10
    environment:
        POSTGRES_PASSWORD: Password12!
        POSTGRES_USER: postgres

pool:
  vmImage: 'ubuntu-16.04'

services:
  postgres: pg10

steps:
- script: |
    sudo apt install -y postgresql-client
    psql --host=postgres --username=postgres --command="SELECT 1;"