resources:
  containers:
  - container: pg10
    image: postgres:10
    environment:
        POSTGRES_PASSWORD: Password12!
        POSTGRES_USER: postgres

pool:
  vmImage: 'win1803'

services:

  pg10: pg10

steps:
  - checkout: none

  - script: |
      psql -h pg10 -c 'create database testdata;' -U postgres;