variables:
  solution: 'linq2db.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Azure'

trigger:
  - master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - script: dotnet test ./Tests/Linq/Tests.csproj -c Azure -f netcoreapp2.0 --logger "trx" --filter "TestCategory != FreeText & TestCategory != Explicit & TestCategory != Ignored & TestCategory != WindowsOnly & TestCategory != ActiveIssue"
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VsTest
      testResultsFiles: '**/*.trx'

- job: MacOS
  pool:
    vmImage: 'macOS-10.14'

  steps:
  - script: dotnet test ./Tests/Linq/Tests.csproj -c Azure -f netcoreapp2.0 --logger "trx" --filter "TestCategory != FreeText & TestCategory != Explicit & TestCategory != Ignored & TestCategory != WindowsOnly & TestCategory != ActiveIssue"
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VsTest
      testResultsFiles: '**/*.trx'

- job: Windows_build
  pool:
    vmImage: 'vs2017-win2016'
  displayName: 'Windows (build)'

  steps:
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '4.4.1'
      checkLatest: true

#- powershell: |
#      $filename1 = "SSCERuntime_x86-ENU.msi"
#      $filename2 = "SSCERuntime_x64-ENU.msi"
#      $downloadUrl = "https://download.microsoft.com/download/6/9/5/695ED23C-F40F-420C-98D1-0F752B8D4E2B/1033/"

#      (New-Object Net.WebClient).DownloadFile($downloadUrl+"/x86/"+$filename1, $filename1)
#      (New-Object Net.WebClient).DownloadFile($downloadUrl+"/x64/"+$filename2, $filename2)

#      $job = Start-Job { msiexec /i $filename1 /qn }
#      Wait-Job $job
#      Receive-Job $job

#      $job = Start-Job { msiexec /i $filename2 /qn }
#      Wait-Job $job
#      Receive-Job $job
#  displayName: 'Install SqlCe 4.0 runtime'

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
      command: 'restore'

  - task: MSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: CopyFiles@2
    inputs:
      TargetFolder: '$(build.ArtifactStagingDirectory)'
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: |
        **/Tests/Linq/bin/$(buildConfiguration)/**
        **/DataProviders.json

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(build.ArtifactStagingDirectory)'
      artifactName: '$(buildConfiguration)'

- job: Windows_testfx
  dependsOn: Windows_build
  condition: succeeded()
  pool:
    vmImage: 'vs2017-win2016'
  displayName: 'Windows (netfx tests job1)'

  steps:
  - checkout: none 

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: '$(buildConfiguration)'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: VSTest@2
    inputs:
      testAssemblyVer2: |
       **\$(BuildConfiguration)\net46*\linq2db.Tests.dll
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      otherConsoleOptions: '/Framework:.NETFramework,Version=v4.6 /TestCaseFilter:"TestCategory != Ignored & TestCategory != ActiveIssue & TestCategory != SkipCI"'
    displayName: 'Run tests NET46' 

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VsTest
      testResultsFiles: '**/*.trx'

- job: Windows_testcore
  dependsOn: Windows_build
  condition: succeeded()
  pool:
    vmImage: 'vs2017-win2016'
  displayName: 'Windows (netcore2 tests job1)'

  steps:
  - checkout: none 

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: '$(buildConfiguration)'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/Tests.csproj'

  - task: VSTest@2
    inputs:
      testAssemblyVer2: |
       **\$(BuildConfiguration)\netcoreapp2.0\linq2db.Tests.Core2.dll
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      otherConsoleOptions: '/Framework:.NETCoreApp,Version=v2.0 /TestCaseFilter:"TestCategory != Ignored & TestCategory != ActiveIssue & TestCategory != SkipCI"'
    displayName: 'Run tests Core2.0' 

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VsTest
      testResultsFiles: '**/*.trx'
