resources:
  containers:
  - container: pg11
    image: postgres:11
    environment:
        POSTGRES_PASSWORD: Password12!
        POSTGRES_USER: postgres

pool:
  vmImage: 'ubuntu-16.04'
  #vmImage: 'windows-2019'

#container: mcr.microsoft.com/windows/servercore:1803

steps:
  - checkout: none

  - script: |
       docker run -d -P --name mysql57 -e MYSQL_ROOT_PASSWORD=Password12! -e MYSQL_ROOT_HOST=% mysql/mysql-server:5.7
       until docker exec mysql57 mysql -e 'SELECT 1'; do
          >&2 echo "MySql is unavailable - sleeping"
          sleep 5
       done
       docker exec mysql57 mysql -e 'CREATE DATABASE IF NOT EXISTS testdata DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'
       docker exec mysql57 mysql -u root -e 'GRANT ALL PRIVILEGES ON *.* TO root@localhost IDENTIFIED BY password WITH GRANT OPTION;'
       docker exec mysql57 mysql -u root -e 'SET PASSWORD FOR root@localhost = PASSWORD(Password12!);'
       docker exec mysql57 mysql -u root -e 'FLUSH PRIVILEGES;'
    displayName: Run MySQL container

  - script:
      sudo apt-get -y -f install mysql-client
  - script: |
      mysql --user=root --password=Password12! -e 'SELECT * FROM mysql.user;'