
jobs:
- job: RunInContainer
  pool:
    vmImage: 'vs2017-win2016'

  steps:
    - checkout: none

    - powershell: |
        choco install postgresql10 --force --params '/Password:password'
        set PATH=%PATH%;"C:\Program Files\PostgreSQL\10\bin;C:\Program Files\PostgreSQL\10\lib"
      displayName: Install postgresql

    - script: start 'C:\Program Files\PostgreSQL\9.5\bin\createdb TestDatanet45'

    - script: printenv
