resources:
  containers:
  - container: pg11
    image: postgres:11
    environment:
        POSTGRES_PASSWORD: Password12!
        POSTGRES_USER: postgres

pool:
  vmImage: 'ubuntu-16.04'
  #vmImage: 'vs2017-win2016'

#container: mcr.microsoft.com/windows/servercore:1803

steps:
  - checkout: none

  - script: |
       docker run -d --name firebird -p 3050:3050 -v /data/firebird/databases:/databases --env ISC_PASSWORD=Password12! --env FIREBIRD_DATABASE=testdata jacobalberty/firebird
       until IF NOT EXIST "localhost:/databases/testdata.fdb"; do
          >&2 echo "firebird is unavailable - sleeping"
          sleep 5
        done
    displayName: Run firebird container


