resources:
  containers:
  - container: pg11
    image: postgres:11
    environment:
        POSTGRES_PASSWORD: Password12!
        POSTGRES_USER: postgres

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - checkout: none

  - script: |
       docker run -d --name postgres10 -e POSTGRES_PASSWORD=Password12! -p 5432:5432 postgres:9.6
       docker exec -it postgres10 psql pfe -U postgres -c "create database my_database"