resources:
  containers:
  - container: my_container
    image: ubuntu:16.04
    options: --hostname localhost --ip 192.168.0.1

  - container: pg10
    image: postgres:10
    environment:
        POSTGRES_PASSWORD: Password12!
        POSTGRES_USER: postgres

pool:
  vmImage: 'ubuntu-16.04'

container: my_container

services:
  postgres: pg10

steps:
  - script: |
      apt-get install -y postgresql-client
      psql --host=192.168.0.1 --username=postgres --command="SELECT 1;"