
jobs:
- job: RunInContainer
  pool:
    vmImage: 'vs2017-win2016'

  steps:
    - checkout: none

    - powershell: |
        $env:MYSQL_PWD="Password12!"
        $dbName = "TestDatanet45"

        choco install mysql --params "/port:3306 /installLocation:'C:'"
        $cmd = '"C:\mysql\current\bin\mysql" -e "create database $dbName;" --user=root'
        iex "& $cmd"
      displayName: Install mysql

    - script: printenv
