resources:
  containers:
  - container: pg11
    image: postgres:11
    environment:
        POSTGRES_PASSWORD: Password12!
        POSTGRES_USER: postgres

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - checkout: none

  - script: |
      docker pull postgres
      docker run --name some-postgres -e POSTGRES_PASSWORD=Password12! -d postgres
      docker run postgres psql -h localhost -c 'create database testdata;' -U postgres