resources:
  containers:
  - container: pg11
    image: postgres:11
    environment:
        POSTGRES_PASSWORD: Password12!
        POSTGRES_USER: postgres

pool:
  vmImage: 'win1803'

services:

  pg10: pg11

steps:
  - checkout: none

  - script: |
      psql -h pg11 -c 'create database testdata;' -U postgres;